version: 0.0
os: linux

#--------------------------------------------------------------
#appspec.yml이 있는 디렉터리의 루트부터 있는 모든 파일을 현 EC2 Instance의 destination 아래에 모두 설치
#--------------------------------------------------------------
files:
  - source: /
    destination: /home/ec2-user/codedeploy/frontend-vue3-demo

#file_exists_behavior: DISALLOW|OVERWRITE|RETAIN    
file_exists_behavior: OVERWRITE

hooks:
#--------------------------------------------------------------
#docker build 및 push 까지는 Jenkins 또는 Terminal 작업 후 진행하기 때문에 apterInstall Option만 사용
#--------------------------------------------------------------
#  BeforeInstall:
#    - location: codedeploy-scripts/dfpcen-dx-guide-before-install.sh
#      timeout: 300
#      runas: root

  AfterInstall:
    - location: codedeploy-scripts/frontend-vue3-demo-after-install.sh
      timeout: 300
      runas: ec2-user

#  ApplicationStart:
#    - location: codedeploy-scripts/dfpcen-dx-guide-application-start.sh
#      timeout: 300
#      runas: root



#  ApplicationStop:
#    - location: scripts/stop_server.sh
#      timeout: 300
#      runas: root
